name: vpn-ping 2
on:
  workflow_dispatch: # para lanzarlo manualmente

jobs:
  ping-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Crear configuración wg0.conf
        run: |
          echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
          sudo chmod 600 wg0.conf

      - name: Levantar túnel WireGuard
        run: |
          sudo wg-quick up ./wg0.conf
          sudo wg show

      - name: Ver interfaces
        run: ip a show wg0

      - name: Probar ping a 172.32.0.1
        run: ping -c 4 172.32.0.1

      - name: Bajar túnel al terminar
        if: always()
        run: sudo wg-quick down ./wg0.conf
